### PR TITLE
add command finish_psbt

### PR DESCRIPTION
**Pull request by nodestory**
User story: bitmark-inc/autonomy#388

Add the command `finish_psbt` which will replace the API request `POST /api/tx/send-tx-in-pbst`.

Additional changes:
- Fix the command name (use snake case).

### CODE REVIEW

**Review by hxw — APPROVED** [review]
Are all the relevant commands converted to snake_case now?

**Comment by lemonlatte** [comment]
> Are all the relevant commands converted to snake_case now?

I think it is a good change because of these reasons:
1. We exchanges data in JSON format, and the snake case seems be widely used in our codebase. For example, we use `json:"snake_case"` in lots of our structures.
2. Some of the command is originally inherit from bitcoin, for example, `createwallet`. For those commands we learn from bitcoin-core, we know what it is and basically accepted. But for our own command, it is more readable no matter in camel case or in snake case.

**Comment by nodestory** [comment]
> Are all the relevant commands converted to snake_case now?

Yes.

**Review by lemonlatte — COMMENTED** [review]
There are lots of errors for `Unmarshal` and `Marshal` is not caught in `finishPSBT`. That means we rely on the upstream function calls to guarantee its output will never go wrong. It might or might not be a problem in the future. Just point out there are some risks here.

**Comment by nodestory** [comment]
I added the prevention check on `json.Unmarshal`. The `json.Marshal` is applied on the `btcjson.String` and it's OK to skip the check.

**Pull request merged**
